version: '3'

services:

  mysql-development:
    image: mysql:8.0.30
    environment:
      MYSQL_ROOT_PASSWORD: devved
      MYSQL_DATABASE: swapi
      MYSQL_ROOT_HOST: "%"
    ports:
      - "3308:3306"
    volumes:
      - container-volume:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/dump.sql

volumes:
  container-volume:
